debug: false
title: "&c&lFolfScoreboard"
updateEveryXSeconds: 1
lines:
  - ""
  - "&fLevel: &a0"
  - "&fPower: &a5/5"
  - ""
  - "#FactionsHook#"
  - ""
  - "&fCoins: &a0"
  - "&fCash: &a0.0"
  - ""
  - "&echeckium.me"
hooks:
  FactionsHook:
    nofaction:
      - "&7Sem Facção"
    hasfaction:
      - "&eTeamOP"
      - " &fOnline: &e1/15"
      - " &fPoder: &e7/7"
      - " &fTerras: &e1"